name: Playwright Tests
on:
  push:
    branches: [playwright-github-actions]
  pull_request:
    branches: [playwright-github-actions]

jobs:
  get_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get branch name
        id: branch_name
        run: 'Branch name is: ${{ github.ref }}'

  test_e2e:
    name: Playwright tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Prepare testing env
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install -g yarn
      - run: yarn ci
      - run: yarn playwright install --with-deps
      - name: Run tests
        run: yarn playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.branch_name.outputs }}
