name: Playwright Tests
on:
  push:
    branches: [playwright-github-actions]
  pull_request:
    branches: [playwright-github-actions]

jobs:
  get_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        id: extract_branch

  test_e2e:
    needs: get_branch_name
    name: Playwright tests
    timeout-minutes: 5
    runs-on: ubuntu-latest
    steps:
      - name: Prepare testing env
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install ci
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run tests
        run: npx playwright test
        env:
          PLAYWRIGHT_TEST_BASE_URL: ${{ steps.extract_branch.outputs.branch }}
