name: Playwright Tests
on:
  push:
    branches: [playwright-github-actions]
  pull_request:
    branches: [playwright-github-actions]
  deployment_status:

jobs:
  get_branch_name:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}"
        id: extract_branch

  test_e2e:
    needs: get_branch_name
    name: Playwright tests
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Wait / Sleep Action
        uses: GuillaumeFalourd/wait-sleep-action@v1
        with:
          time: '7m'
      - name: Prepare testing env
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18'
      - run: npm install ci
      - run: npm ci
      - run: npx playwright install --with-deps
      - name: Run tests
        env:
          username: ${{ vars.USERNAME}}
          password: ${{ vars.PASSWORD}}
          BASE_URL: ${{ github.event.deployment_status.target_url }}
        run: npx playwright test
